<a href="https://colab.research.google.com/github/syedibrahimt/np_pd/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello to the world of numpy")

Hello to the world of numpy


In [3]:
import numpy as np

array_1d = np.asarray(range(5))

In [4]:
print(array_1d)

[0 1 2 3 4]


In [5]:
array_2d = np.asarray([range(4), range(4)])

In [6]:
print(array_2d)

[[0 1 2 3]
 [0 1 2 3]]


In [7]:
array_2d.ndim

2

In [12]:
print(array_1d.shape)
print(array_2d.shape)

(5,)
(2, 4)
